## Página principal
GET http://localhost:3003

## Todas las prendas

GET http://localhost:3003/prendas

## Prenda por id

GET http://localhost:3003/prendas/6681b93edbdb53d6f6067e4e

## Prenda por nombre 

GET http://localhost:3003/prendas?nombre=Jeans

## Agregar un producto
POST http://localhost:3003/prendas
Content-Type: application/json
{
  "codigo": 131,
  "nombre": "Pollera Cuero",
  "precio": 49.99,
  "categoria": "Outfit"
}

## Modificar precio de un producto por _id
PATCH http://localhost:3003/prendas/6681b93edbdb53d6f6067e44
Content-Type: application/json

{

  "precio": 130.45

}

## Se elimina una prenda por _id
DELETE http://localhost:3003/prendas/6681b93edbdb53d6f6067e5e


## Creación de token usando JWT
POST http://localhost:3003/register
Content-Type: application/json

{
  "email": "usuario@example.com",
  "password": "contraseña"
}

## Login de usuario 
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "usuario@example.com",
    "password": "contraseña"
}